AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./deploy/api.yaml
      StageName: test
      Variables:
        LambdaFunctionName: !Ref ResizeFunction

  ResizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/function.zip
      Handler: index.handler
      Runtime: nodejs6.10
      MemorySize: 1536
      Timeout: 60

  ResizeFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ResizeFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*
